DEBUG=True


SQLALCHEMY_DATABASE_URI='sqlite:///data.db'
SQLALCHEMY_TRACK_MODIFICATIONS=False
SECRET_KEY='QS3-CX5-RF9'

USER_SERVICE_NAME='user'
MOVIE_LIBRARY_SERVICE_NAME='movie_library'

USER_PORT='5000'
MOVIE_LIBRARY_PORT='5001'
